FROM python:3.9-slim

WORKDIR /app

# Installation des outils réseau
RUN apt-get update && apt-get install -y \
    nmap \
    masscan \
    && rm -rf /var/lib/apt/lists/*

# Installation des dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/modules/network/ /app/network/

ENV PYTHONPATH=/app

CMD ["python", "/app/network/service.py"]