FROM python:3.9-slim

WORKDIR /app

# Installation des outils OSINT
RUN apt-get update && apt-get install -y \
    whois \
    dig \
    && rm -rf /var/lib/apt/lists/*

# Installation des dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Installation de TheHarvester
RUN pip install theHarvester

COPY src/modules/osint/ /app/osint/

ENV PYTHONPATH=/app

CMD ["python", "/app/osint/service.py"]