apiVersion: apps/v1
kind: Deployment
metadata:
  name: testudo-osint
  labels:
    app: testudo
    component: osint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testudo
      component: osint
  template:
    metadata:
      labels:
        app: testudo
        component: osint
    spec:
      containers:
      - name: osint
        image: testudo/osint:latest
        env:
        - name: COORDINATOR_URL
          value: http://testudo-coordinator:8080
        ports:
        - containerPort: 8081